### ISSUE TITLE
Method Name

### ISSUE THREAD

**Issue by brianorwhatever** [bcgov/didwebnext#1]
If a goal of the method is to be agnostic to backing storage I don't think "web" should be in the name. I also think `webnext` is too long I prefer 3-4 characters max.

Unfortunately, I see that `did:next` is [taken](https://docs.nextme.one/#/DID/NextDID)

**Comment by swcurran** [comment]
`webnext` is a placeholder name only and not intended for any other purpose than a way to create a repo.

Naming is hard and will come much later.
