### ISSUE TITLE
Include metadata about the DID in the DIDDoc

### ISSUE THREAD

**Issue by swcurran** [bcgov/didwebnext#12]
Include in the DIDDoc the following information:

* versionId (required). Must be 0 for the initial DIDDoc and incremented per DIDDoc update.
* created — a locally defined (by the DID controller) time when the initial DIDDoc was created.
* updated — a locally defined (by the DID controller) time when this DIDDoc was created.
* previousProof — the proof item from the previous version of the DIDDoc.
    * An empty array `[]` for the initial DIDDoc.

**Comment by swcurran** [comment]
Sounds good — I’ll update the description.

**Comment by andrewwhitehead** [comment]
Just to add, the DID Core spec defines `created`, `updated` and `versionId` as document metadata that are not (normally) included in the document itself. But I don't see why they couldn't be.

**Comment by andrewwhitehead** [comment]
I think we're leaning toward removing these from the document to avoid using a custom `@context`.

- `previousHash` would be stored in the log
- `created` would be the first timestamp in the log
- `updated` would be the latest
- `versionId` would be the line number

We would need to hash the `previousHash` and `timestamp` into the CID, and likely set the `domain` of the proofs to the CID to tie them together.

**Comment by swcurran** [comment]
Resolved by the log format #20 .
