### ISSUE TITLE
Document Format

### ISSUE THREAD

**Issue by brianorwhatever** [bcgov/didwebnext#4]
Proposals:

## Proposal 1: something very DID docy

Benefits:
- Easy parsing at resolution time
Drawbacks:
- Large file size

```json
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/multikey/v1"
  ],
  "authentication": ["#z6Mko4t2y5Pbx96hbQP5p8JkJXA3z16nAq7VpUyZGcjhd9ra"],
  "capabilityInvocation": ["#z6MkqHVcPwdxaNnwAYEi1ZrqE1z3EonVdZ6hmGFXz9wSHqUB"],
  "capabilityDelegation": ["#z6Mkhn3U7DCskv9SzLW8Fwa3ssYhwjzZMTPj443RqMmaBKYb"],
  "assertionMethod": ["#z6MkmUNA3PrAr28xhofDKMN6So2tjsC2HoohsJzMwejXuxAm"],
  "verificationMethod": [{
      "id": "#z6Mko4t2y5Pbx96hbQP5p8JkJXA3z16nAq7VpUyZGcjhd9ra",
      "type": "Multikey",
      "publicKeyMultibase": "z6Mko4t2y5Pbx96hbQP5p8JkJXA3z16nAq7VpUyZGcjhd9ra"
    }, {
      "id": "#z6MkqHVcPwdxaNnwAYEi1ZrqE1z3EonVdZ6hmGFXz9wSHqUB",
      "type": "Multikey",
      "publicKeyMultibase": "z6MkqHVcPwdxaNnwAYEi1ZrqE1z3EonVdZ6hmGFXz9wSHqUB"
    }, {
      "id": "#z6Mkhn3U7DCskv9SzLW8Fwa3ssYhwjzZMTPj443RqMmaBKYb",
      "type": "Multikey",
      "publicKeyMultibase": "z6Mkhn3U7DCskv9SzLW8Fwa3ssYhwjzZMTPj443RqMmaBKYb"
    }, {
      "id": "#z6MkmUNA3PrAr28xhofDKMN6So2tjsC2HoohsJzMwejXuxAm",
      "type": "Multikey",
      "publicKeyMultibase": "z6MkmUNA3PrAr28xhofDKMN6So2tjsC2HoohsJzMwejXuxAm"
    }],
  "service": [{
    "id": "#didcomm-1",
    "type": "DIDCommMessaging",
    "serviceEndpoint": {
        "uri": "https://example.com/path",
        "accept": [
            "didcomm/v2",
            "didcomm/aip2;env=rfc587"
        ],
        "routingKeys": ["did:example:somemediator#somekey"]
    }
  }, {
    "id": "#linked-vp",
    "type": "LinkedVerifiablePresentation",
    "serviceEndpoint": ["https://bar.example.com/verifiable-presentation.jsonld"]
  }]
}
```

## Proposal 2: Something like [selfhash](https://github.com/LedgerDomain/selfhash?tab=readme-ov-file#example-1----simplest)

Benefits: 
- Uses well defined placeholder slots
- Others are using it so presumably it works
- Comes predesigned with a microledger
Drawbacks:
- Not sure on flexibility

`{"data_byte_v":[1,2,4,8,16,32,64,128],"name":"grippoponkey","previous":"Eyl1ZXOe_nOufcpisvlW1ZUeXKnY_kIKOOljEhMAd5zw","self_hash":"Ew4c7NoEyI842yfIxBakoWgCYI6v4nAQp1Z1OtHzOiFQ","stuff_count":43}`

## Proposal 3: Custom encoded like [did:peer](https://identity.foundation/peer-did-method-spec/#method-2-multiple-inception-key-without-doc)

Benefits:
- Compact
Drawbacks:
- Need to define microledger approach

`Vz6Mkj3PUd1WjvaDhNZhhhXQdz5UnZXmS7ehtx8bsPpD47kKc.Ez6LSg8zQom395jKLrGiBNruB9MM6V8PWuf2FpEy4uRFiqQBR.SeyJ0IjoiZG0iLCJzIjp7InVyaSI6Imh0dHA6Ly9leGFtcGxlLmNvbS9kaWRjb21tIiwiYSI6WyJkaWRjb21tL3YyIl0sInIiOlsiZGlkOmV4YW1wbGU6MTIzNDU2Nzg5YWJjZGVmZ2hpI2tleS0xIl19fQ.SeyJ0IjoiZG0iLCJzIjp7InVyaSI6Imh0dHA6Ly9leGFtcGxlLmNvbS9hbm90aGVyIiwiYSI6WyJkaWRjb21tL3YyIl0sInIiOlsiZGlkOmV4YW1wbGU6MTIzNDU2Nzg5YWJjZGVmZ2hpI2tleS0yIl19fQ`

Any other proposals?

**Comment by swcurran** [comment]
I think we start with the assumption that each DIDDoc is the full document, and every document can be resolved using:

- <did> — get the latest version
- <did>?versionId=0 — get the initial version
- <did>?versionId=<n> — get the nth version

It would be very helpful to be able to get all of the DIDDocs in a single request — ideally in some compressed form, such as gzip.

It would be nice to be able to support `versionTime` to get the version of the DIDDoc active at the given time (according to the DIDDoc controller).

**Comment by brianorwhatever** [comment]
Sounds like we agree proposal 1 is the way to go. It will be a very DIDDocumenty looking document that everything is based off of.

I've started to think including all of the previous hashes whether in merkle paths or a simple list of hashes isn't required like I previously thought. This can be handled at the implementation & indexing level. But this means we still need some sort of way to refer to the previous version's hash/cid to form the microledger. I think `versionId` is that place. So at any given state the `versionId` is the current hash and `prevVersionId` is the previous version's hash (or `null` in the inception case). Is there any reason we would need incremental versions other than for blindly iterating through versions?

I think 1 learning from reading between the lines of the `did:plc` spec is that they now have a single operation for create/update where they used to have a separate create operation that they regrettably have to continue to support forever. Ideally we can ensure that create/update are the same operation other then the few key differences.

**Comment by swcurran** [comment]
I think it makes more sense to add an extra field `prevHash` vs. overriding `versionId` so that we get the benefit of being able to walk through them with simple GETs.  We can figure that out.

Interesting observation about the create/update in the `did:plc` spec. Something to keep in mind!

**Comment by brianorwhatever** [comment]
This issue is no longer relevant as we are using a **Log** mechanism now that resolves into a DID Document using JSON Patch.
